# CONFIG
tagFormat: "${version}"

_rules: &rules
  - type: '*!'
    release: major
  - type: chore
    scope: api-deps
    release: minor
  - type: chore
    scope: core-deps
    release: patch
  - type: docs
    release: patch
  - type: revert
    release: patch

_types: &types
  - type: '*!'
    section: "BREAKING CHANGES"
  - type: feat
    section: "Features"
  - type: chore
    scope: api-deps
    section: "Dependency updates"
  - type: chore
    scope: core-deps
    release: patch
    section: "Dependency updates"
  - type: chore
    scope: deps
    section: "Dependency updates"
  - type: fix
    section: "Bug Fixes"
  - type: docs
    section: "Documentation"
  - type: perf
    section: "Performance improvements"
  - type: revert
    section: "Revert previous changes"
  - type: test
    section: "Tests"
  - type: ci
    section: "Build and continuous integration"
  - type: build
    section: "Build and continuous integration"
  - type: chore
    section: "General maintenance"
  - type: style
    section: "Style improvements"
  - type: refactor
    section: "Refactoring"
# ENDCONFIG
plugins:
  -
    - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      presetConfig:
        types: *types
      releaseRules:
        *rules
### TEST ###
  -
    - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types: *types
  - "@semantic-release/changelog"
### CUT ###
  - "@semantic-release/npm"
  - "@semantic-release/github"
  -
    - "@semantic-release/git"
    - assets:
      - '*.md'
      - '*.json'
  -
    - "@semantic-release/exec"
    - prepareCmd: |
        mv .releaserc.json.pre .releaserc.json
